# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class Candle(BaseModel):
    """
    Abbreviated candle format. Zero values are omitted.
    """ # noqa: E501
    t: StrictInt = Field(description="Timestamp")
    o: Union[StrictFloat, StrictInt] = Field(description="Open price")
    h: Union[StrictFloat, StrictInt] = Field(description="High price")
    l: Union[StrictFloat, StrictInt] = Field(description="Low price")
    c: Union[StrictFloat, StrictInt] = Field(description="Close price")
    v: Union[StrictFloat, StrictInt] = Field(description="Base token volume (volume0)")
    V: Union[StrictFloat, StrictInt] = Field(description="Quote token volume (volume1)", alias="V")
    i: StrictInt = Field(description="Last trade ID")
    C: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description=" close_raw", alias="C")
    H: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description=" high_raw", alias="H")
    L: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description=" low_raw", alias="L")
    O: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description=" open_raw", alias="O")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["t", "o", "h", "l", "c", "v", "V", "i", "C", "H", "L", "O"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Candle from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Candle from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_construct(**{
            "t": obj.get("t"),
            "o": obj.get("o"),
            "h": obj.get("h"),
            "l": obj.get("l"),
            "c": obj.get("c"),
            "v": obj.get("v"),
            "V": obj.get("V"),
            "i": obj.get("i"),
            "C": obj.get("C"),
            "H": obj.get("H"),
            "L": obj.get("L"),
            "O": obj.get("O")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


