# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from lighter.models.contract_address import ContractAddress
from lighter.models.l1_provider_info import L1ProviderInfo
from lighter.models.validator_info import ValidatorInfo
from typing import Optional, Set
from typing_extensions import Self

class Layer1BasicInfo(BaseModel):
    """
    Layer1BasicInfo
    """ # noqa: E501
    code: StrictInt
    message: Optional[StrictStr] = None
    l1_providers: List[L1ProviderInfo]
    l1_providers_health: StrictBool
    validator_info: List[ValidatorInfo]
    contract_addresses: List[ContractAddress]
    latest_l1_generic_block: StrictInt
    latest_l1_governance_block: StrictInt
    latest_l1_desert_block: StrictInt
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["code", "message", "l1_providers", "l1_providers_health", "validator_info", "contract_addresses", "latest_l1_generic_block", "latest_l1_governance_block", "latest_l1_desert_block"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Layer1BasicInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in l1_providers (list)
        _items = []
        if self.l1_providers:
            for _item in self.l1_providers:
                if _item:
                    _items.append(_item.to_dict())
            _dict['l1_providers'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in validator_info (list)
        _items = []
        if self.validator_info:
            for _item in self.validator_info:
                if _item:
                    _items.append(_item.to_dict())
            _dict['validator_info'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in contract_addresses (list)
        _items = []
        if self.contract_addresses:
            for _item in self.contract_addresses:
                if _item:
                    _items.append(_item.to_dict())
            _dict['contract_addresses'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Layer1BasicInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_construct(**{
            "code": obj.get("code"),
            "message": obj.get("message"),
            "l1_providers": [L1ProviderInfo.from_dict(_item) for _item in obj["l1_providers"]] if obj.get("l1_providers") is not None else None,
            "l1_providers_health": obj.get("l1_providers_health"),
            "validator_info": [ValidatorInfo.from_dict(_item) for _item in obj["validator_info"]] if obj.get("validator_info") is not None else None,
            "contract_addresses": [ContractAddress.from_dict(_item) for _item in obj["contract_addresses"]] if obj.get("contract_addresses") is not None else None,
            "latest_l1_generic_block": obj.get("latest_l1_generic_block"),
            "latest_l1_governance_block": obj.get("latest_l1_governance_block"),
            "latest_l1_desert_block": obj.get("latest_l1_desert_block")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


