# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self

class OrderBook(BaseModel):
    """
    OrderBook
    """ # noqa: E501
    symbol: StrictStr
    market_id: StrictInt
    market_type: StrictStr
    base_asset_id: StrictInt
    quote_asset_id: StrictInt
    status: StrictStr
    taker_fee: StrictStr
    maker_fee: StrictStr
    liquidation_fee: StrictStr
    min_base_amount: StrictStr
    min_quote_amount: StrictStr
    supported_size_decimals: StrictInt
    supported_price_decimals: StrictInt
    supported_quote_decimals: StrictInt
    order_quote_limit: StrictStr
    is_maker_fee_enabled: StrictBool
    is_taker_fee_enabled: StrictBool
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["symbol", "market_id", "market_type", "base_asset_id", "quote_asset_id", "status", "taker_fee", "maker_fee", "liquidation_fee", "min_base_amount", "min_quote_amount", "supported_size_decimals", "supported_price_decimals", "supported_quote_decimals", "order_quote_limit", "is_maker_fee_enabled", "is_taker_fee_enabled"]

    @field_validator('market_type')
    def market_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['perp', 'spot']):
            raise ValueError("must be one of enum values ('perp', 'spot')")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['inactive', 'active']):
            raise ValueError("must be one of enum values ('inactive', 'active')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OrderBook from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OrderBook from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_construct(**{
            "symbol": obj.get("symbol"),
            "market_id": obj.get("market_id"),
            "market_type": obj.get("market_type"),
            "base_asset_id": obj.get("base_asset_id"),
            "quote_asset_id": obj.get("quote_asset_id"),
            "status": obj.get("status"),
            "taker_fee": obj.get("taker_fee"),
            "maker_fee": obj.get("maker_fee"),
            "liquidation_fee": obj.get("liquidation_fee"),
            "min_base_amount": obj.get("min_base_amount"),
            "min_quote_amount": obj.get("min_quote_amount"),
            "supported_size_decimals": obj.get("supported_size_decimals"),
            "supported_price_decimals": obj.get("supported_price_decimals"),
            "supported_quote_decimals": obj.get("supported_quote_decimals"),
            "order_quote_limit": obj.get("order_quote_limit"),
            "is_maker_fee_enabled": obj.get("is_maker_fee_enabled"),
            "is_taker_fee_enabled": obj.get("is_taker_fee_enabled")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


