# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self

class Token(BaseModel):
    """
    Token
    """ # noqa: E501
    symbol: StrictStr
    name: StrictStr
    logo: StrictStr
    logo_extension: StrictStr
    description_key: StrictStr
    gecko_id: StrictStr
    paprika_id: StrictStr
    market: StrictStr
    asset_type: StrictStr
    categories: List[StrictStr]
    is_allowed_mainnet: StrictBool
    is_asset_allowed_mainnet: StrictBool
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["symbol", "name", "logo", "logo_extension", "description_key", "gecko_id", "paprika_id", "market", "asset_type", "categories", "is_allowed_mainnet", "is_asset_allowed_mainnet"]

    @field_validator('logo_extension')
    def logo_extension_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['svg', 'png']):
            raise ValueError("must be one of enum values ('svg', 'png')")
        return value

    @field_validator('market')
    def market_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['SPOT', 'PERPS']):
            raise ValueError("must be one of enum values ('SPOT', 'PERPS')")
        return value

    @field_validator('asset_type')
    def asset_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['CRYPTO', 'RWA']):
            raise ValueError("must be one of enum values ('CRYPTO', 'RWA')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Token from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Token from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_construct(**{
            "symbol": obj.get("symbol"),
            "name": obj.get("name"),
            "logo": obj.get("logo"),
            "logo_extension": obj.get("logo_extension"),
            "description_key": obj.get("description_key"),
            "gecko_id": obj.get("gecko_id"),
            "paprika_id": obj.get("paprika_id"),
            "market": obj.get("market"),
            "asset_type": obj.get("asset_type"),
            "categories": obj.get("categories"),
            "is_allowed_mainnet": obj.get("is_allowed_mainnet"),
            "is_asset_allowed_mainnet": obj.get("is_asset_allowed_mainnet")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


